### ISSUE TITLE
IPT architecture doesn't define total issuance to get a threshold of

### ISSUE THREAD

**Issue by arrudagates** [InvArch/InvArch-Frames#146]
In IPT we used to define execution threshold as `total_issuance / threshold`, but with the introduction of sub assets which can also vote, it's necessary to redefine where the total issuance comes from, the ups and downsides of each approach need to be evaluated. Some of the possible approaches include:
- Just using the root IPT's issuance
- Using the issuance of root IPT + all sub assets
- Using only the issuance of all assets present in the multisig operation
- Having a formula that uses the issuance of all assets but takes their weights in consideration

**Comment by arrudagates** [comment]
@S0raWasTaken I want you to explore swapping the total issuance used to get the threshold (root ipt issuance) with the following: `root ipt issuance + (<sub asset issuance> * <the sub asset's respective weight>)` adding up every sub asset.
For example, for an IPT that has 1 root ipt, 1 sub asset 0 with weight 0.1 and 2 sub asset 1 with weight 0.05, the total issuance following the formula becomes `1 + (1 * 0.1) + (2 * 0.05) = 1.2`

**Comment by S0raWasTaken** [comment]
Closed by #148
